# ==========================================
# Development Profile
# ==========================================

spring.data.mongodb.uri=mongodb://localhost:27017/copro-connect-dev

logging.level.root=DEBUG
logging.level.com.copro=DEBUG
logging.level.org.springframework.data.mongodb.core=DEBUG

# Désactiver la sécurité CSRF en développement (si nécessaire)
spring.security.filter.dispatcher-types=REQUEST,ERROR

# Dev Tools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
